import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { EnquireModalProvider } from "./components/common/EnquireModalProvider";
import { SiteVisitModalProvider } from "./components/common/SiteVisitModalProvider";
import { WorkWithUsModalProvider } from "./components/common/WorkWithUsModalProvider";
import { FloatingBottomActions } from "./components/common/FloatingBottomActions";
import { HomeGatewayProvider } from "./components/common/HomeGatewayProvider";
import { SmoothScrollProvider } from "./components/common/SmoothScrollProvider";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  title: "Sanskar Group",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/sankar_favicon.png",
  },
  verification: {
    google: "VibyxJ5f3UQQlcKNxVNcL3Tl7M5OpIvzPKBgvqbAi3k",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-13RSCDVFE1"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-13RSCDVFE1');
          `}
        </Script>
      </head>
      <body className="min-h-full bg-white antialiased" suppressHydrationWarning>
        <SmoothScrollProvider>
          <EnquireModalProvider>
            <WorkWithUsModalProvider>
              <SiteVisitModalProvider>
                <HomeGatewayProvider>
                  {children}
                  <FloatingBottomActions />
                </HomeGatewayProvider>
              </SiteVisitModalProvider>
            </WorkWithUsModalProvider>
          </EnquireModalProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
